name: machine-learning-hats-2020
channels:
    - conda-forge
    - defaults
dependencies:
    - uproot
    - matplotlib
    - pandas
    - ipykernel
    - tqdm
    - jupyter
    - uproot-methods
    - root
    - scipy
    - vector
